"""update

Revision ID: 06be0a1492b4
Revises: a5c75e86d511
Create Date: 2023-12-31 12:42:48.488695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06be0a1492b4'
down_revision = 'a5c75e86d511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_keys', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_keys')

    # ### end Alembic commands ###
